name: Simple Auto Pull

on:
  push:
    branches:
      - main  # 只在 push 到 main 分支時觸發

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]  # 指定自架 runner

    steps:
      - name: 自動更新程式碼
        run: |
          cd /home/ian105102/test
          git reset --hard
          git pull origin main
          echo "✅ 程式碼已自動拉取最新版本！"